name: Build Images

on:
  workflow_call:
    inputs:
      runner-os:
        description: 'Operating system ("ubuntu-22.04")'
        type: string
        required: true
      arch:
        description: 'Architecture ("linux/amd64", "linux/arm64")'
        type: string
        required: true
      cache-key:
        description: 'Cache key'
        type: string
        required: true
      cache-restore-keys:
        description: 'Cache restore keys list'
        type: string
        required: true

jobs:
  build:
    name: Build Image
    runs-on: ${{ inputs.runner-os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ inputs.cache-key }}
          restore-keys: ${{ inputs.cache-restore-keys }}
      - name: Image name
        id: image_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ghcr.io/${{ github.repository }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        if: ${{ !(env.ACT || github.actor == 'dependabot[bot]') }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
        with:
            platforms: ${{ inputs.arch }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Docker meta (runtime)
        id: meta_runtime
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.image_name.outputs.lowercase }}
          flavor: |
            prefix=runtime-,onlatest=true
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr,prefix=runtime-pr-
      - name: Docker meta (builder)
        id: meta_builder
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.image_name.outputs.lowercase }}
          flavor: |
            prefix=builder-,onlatest=true
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr,prefix=builder-pr-
      - name: Docker meta (builder_nodejs)
        id: meta_builder_nodejs
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.image_name.outputs.lowercase }}
          flavor: |
            prefix=builder_nodejs-,onlatest=true
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr,prefix=builder_nodejs-pr-
      - name: Docker meta (vscode)
        id: meta_vscode
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.image_name.outputs.lowercase }}
          flavor: |
            prefix=vscode-,onlatest=true
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr,prefix=vscode-pr-
      - name: Build and push (runtime)
        uses: docker/build-push-action@v5
        with:
          push: ${{ !(env.ACT || github.actor == 'dependabot[bot]') }}
          context: .
          platforms: ${{ inputs.arch }}
          target: runtime
          tags: ${{ steps.meta_runtime.outputs.tags }}
          labels: ${{ steps.meta_runtime.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and push (builder)
        uses: docker/build-push-action@v5
        with:
          push: ${{ !(env.ACT || github.actor == 'dependabot[bot]') }}
          context: .
          platforms: ${{ inputs.arch }}
          target: builder
          tags: ${{ steps.meta_builder.outputs.tags }}
          labels: ${{ steps.meta_builder.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and push (builder_nodejs)
        uses: docker/build-push-action@v5
        with:
          push: ${{ !(env.ACT || github.actor == 'dependabot[bot]') }}
          context: .
          platforms: ${{ inputs.arch }}
          target: builder_nodejs
          tags: ${{ steps.meta_builder_nodejs.outputs.tags }}
          labels: ${{ steps.meta_builder_nodejs.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Build and push (vscode)
        uses: docker/build-push-action@v5
        with:
          push: ${{ !(env.ACT || github.actor == 'dependabot[bot]') }}
          context: .
          platforms: ${{ inputs.arch }}
          target: vscode
          tags: ${{ steps.meta_vscode.outputs.tags }}
          labels: ${{ steps.meta_vscode.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
        # Temp fix?
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
